# Generated by Django 5.1.3 on 2024-11-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('holidayType', models.IntegerField(choices=[(0, 'temp'), (1, 'christmas'), (2, 'new years'), (3, 'thanksgiving'), (4, 'birthdays')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
