# Generated by Django 5.1.3 on 2024-11-28 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalcardmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_hash_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
